# Generated by Django 2.0 on 2019-06-12 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('anchor', models.CharField(max_length=256)),
                ('strength', models.FloatField()),
                ('last_seen', models.DateField()),
                ('first_seen', models.DateField()),
                ('days_survived', models.FloatField()),
                ('re_introductions', models.PositiveIntegerField()),
                ('revision_survived', models.PositiveIntegerField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
