# Generated by Django 2.0 on 2019-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_article_total_anchor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='days_survived',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='first_seen',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='last_seen',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='re_introductions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='revision_survived',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anchor',
            name='strength',
            field=models.FloatField(null=True),
        ),
    ]
