# Generated by Django 2.0 on 2019-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_article_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
