# Generated by Django 2.0 on 2019-10-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191020_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='revision_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='anchor',
            name='revision_start_date',
            field=models.DateField(null=True),
        ),
    ]
